name: page compilation
on:
  push:
    branches: [ main ]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - run: sudo apt-get install -y build-essential pandoc jq
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - run: make -C root
      - name: set up pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './root'
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: compile
    permissions:
      pages: write
      id-token: write
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
